export const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    profile: "/auth/me",
    changePassword: "/auth/change-password",
    updateProfile: "/auth/update-profile",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  foods: "/foods",
  fridge: "/fridge-items",
  families: "/families",
  shopping: "/shopping-lists",
  shoppingItems: "/shopping-list-items",
  recipes: "/recipes",
  recipeSuggestions: "/recipes/suggestions",
  mealPlans: "/meal-plans",
};
