module.exports = {
  tables: {
    item: 'fridge_items',
    food: 'foods',
    category: 'food_categories',
    unit: 'units',
    family: 'family_groups',
    member: 'group_members',
    user: 'users',
  },
  columns: {
    itemId: 'id',
    userId: 'user_id',
    foodName: 'food_name',
    itemName: 'name',
    foodId: 'id',
    itemFoodId: 'food_id',
    quantity: 'quantity',
    unitId: 'unit_id',
    categoryId: 'category_id',
    expiry: 'expiration_date',
    storageLocation: 'storage_location',
    createdAt: 'added_at',
    updatedAt: 'updated_at',
    categoryName: 'name_vi',
    unitName: 'name',
    unitSymbol: 'symbol',
    userName: 'full_name',
    familyId: 'id',
    memberFamilyId: 'group_id',
    memberUserId: 'user_id',
  },
};
