module.exports = {
  tables: {
    recipe: 'recipes',
    ingredient: 'recipe_ingredients',
    favorite: 'favorite_recipes',
    food: 'foods',
    user: 'users',
    fridgeItem: 'fridge_items',
  },
  columns: {
    recipeId: 'id',
    title: 'name_vi',
    titleEn: 'name_en',
    description: 'description',
    instructions: 'instructions',
    prepTime: 'prep_time',
    cookTime: 'cook_time',
    servings: 'servings',
    creatorId: 'created_by',
    isPublic: 'is_public',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    ingredientId: 'id',
    ingredientRecipeId: 'recipe_id',
    ingredientName: 'name',
    quantity: 'quantity',
    unitId: 'unit_id',
    categoryId: 'category_id',
    userId: 'user_id',
  },
};
