/**
 * Schema bảng công thức nấu ăn (tiếng Việt) — khớp Supabase thực tế.
 */
module.exports = {
  tables: {
    recipe: 'cong_thuc',
    recipeCategory: 'danh_muc_cong_thuc',
    ingredient: 'cong_thuc_nguyen_lieu',
    favorite: 'cong_thuc_yeu_thich',
    food: 'thuc_pham',
    family: 'gia_dinh',
    user: 'nguoi_dung',
    fridgeItem: 'chi_tiet_tu_lanh',
    fridge: 'tu_lanh',
  },
  columns: {
    recipeId: 'cong_thuc_id',
    title: 'ten_mon_an',
    description: 'mo_ta',
    instructions: 'huong_dan_nau',
    timeMinutes: 'thoi_gian_phut',
    servings: 'khau_phan',
    imageUrl: 'hinh_anh_url',
    categoryId: 'danh_muc_id',
    categoryPk: 'danh_muc_cong_thuc_id',
    categoryName: 'ten_danh_muc',
    creatorId: 'nguoi_tao_id',
    privacy: 'loai_quyen',
    familyId: 'gia_dinh_id',
    createdAt: 'ngay_tao',
    updatedAt: 'ngay_cap_nhat',
    ingredientId: 'nguyen_lieu_id',
    foodId: 'thuc_pham_id',
    ingredientName: 'ten_nguyen_lieu',
    quantity: 'so_luong',
    unit: 'don_vi',
    sortOrder: 'thu_tu',
    userId: 'nguoi_dung_id',
    userEmail: 'email',
    foodName: 'ten_thuc_pham',
    fridgeId: 'tu_lanh_id',
    fridgeItemId: 'chi_tiet_id',
    familyName: 'ten_gia_dinh',
  },
  defaultFamilyName: 'Gia đình NATEAT',
};
